### ISSUE TITLE
[FEATURE] add 'git init' for new project creation

### ISSUE THREAD

**Issue by stevelr** [wasmCloud/wash#232]
The `wash new actor` command creates a project folder containing a `.cargo` subdirectory. The subdirectory might be overlooked by a developer when checking into git. We may be able to prevent that problem by running `git init` as part of the project creation process, in a way that ensures the `.cargo` subdirectory is included in the repo.

**Comment by stevelr** [comment]
Liam suggested making this optional. If the default is to run  `git init` for project creation, the optional CLI flag would be to disable that step.
(My proposal is to make the default action to run git init. That's what `cargo new` does also).

**Comment by brooksmtownsend** [comment]
I think following `cargo new` as a guide would be best practice for what Rust developers expect from a new project generation tool

**Comment by ghost** [comment]
I'm looking into this, but having some issues. 

It looks like in one case we are already providing a git repo, when someone uses the `wash new actor --git` functionality. That clones the existing repo and then cleans out the commit history (see `create` in [src/generate/git.rs](https://github.com/wasmCloud/wash/blob/main/src/generate/git.rs)). However, I can't find a repo to get that to work on. When I try to grab the example `todo` actor like this:
` wash new actor --git https://github.com/wasmcloud/examples/tree/main/actor/todo`

I get an error in response: `Git Error: unexpected http status code: 404; class=Http (34)`. This happens with any other repo I've tried. Is there an example I can try to get this to work, or is this a bug we need to fix?

Next is the premise of the issue, that we want to make sure developers check in the `.cargo` subdirectory. I looked into how `cargo new` generates projects and while it does initialize a git repository, it doesn't check anything in by default. So this wouldn't alleviate our issue of missing the `.cargo` directory if we went with their approach. Do we want to make a commit automatically when we are generating the actor to make sure all of the initial files are checked in?

The actual implementation of this shouldn't be too hard, as we just need to check if there is a git repository already existing, and if there isn't, initialize a new one. However, we should decide if we want to make that initializing commit first or leave it up to the developer to make sure they check everything in.

**Comment by stevelr** [comment]
Thanks for looking into this. I don't think we need to commit. If the .cargo dir is added by an automatic 'git add' when the files are created, it becomes a little less likely to be overlooked when they do commit.

The git flag is supposed to let you use another template repo. Does it work with any of the subdirs of project-templates?

**Comment by ghost** [comment]
> Thanks for looking into this. I don't think we need to commit. If the .cargo dir is added by an automatic 'git add' when the files are created, it becomes a little less likely to be overlooked when they do commit.
> 
> The git flag is supposed to let you use another template repo. Does it work with any of the subdirs of project-templates?

I still get the error: `⛔   Git Error: unexpected http status code: 404; class=Http (34)` trying to use the echo example in project templates. I'm using it like this:
`wash new actor --git https://github.com/wasmCloud/project-templates/tree/main/actor/echo`
Is this incorrect usage? I'm not sure if the `/tree/main` part messes this up but I've tried it without and also got the same error. Does the `--git` flag only work on a whole repo and not a subdirectory of one?

**Comment by brooksmtownsend** [comment]
@mattwilkinsonn I believe you're looking for the following syntax:
```
wash new actor --git wasmcloud/project-templates --branch main --subfolder actor/echo
```

`--branch` isn't required for `main`, but i left it in there just in case you needed to modify anything
